[package]
name = "struct_update_syntax"
version = "0.1.0"
authors = ["arif"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
