[package]
name = "types_of_errors"
version = "0.1.0"f
authors = ["ArifSanaullah <ak7896023@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
[profile.dev]
panick = 'abort'
